name: CI

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npx biome --version  # グローバルインストールせず、npxで実行

      - name: Lint
        run: npx biome ci .   # npxを使用

      - name: Test
        run: npm test

      - name: Check dependencies
        run: npm run deps:check

      - name: Build
        run: npm run build
