name: Tweet Generator

on:
  schedule:
    # 毎週月曜日の朝6時（JST）= 日曜日の21:00（UTC）
    - cron: '0 21 * * 0'
  workflow_dispatch:
    inputs:
      branch:
        description: '実行するブランチを指定'
        required: false
        default: 'main'
        type: choice
        options:
          - development  # 開発環境
          - main        # 本番環境（デフォルト）

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # GitHub Secretsにアクセスするための最小限の権限
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate and Post Tweet
        run: npm run tweet
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ vars.OPENROUTER_MODEL }}
          OPENROUTER_TEMPERATURE: ${{ vars.OPENROUTER_TEMPERATURE }}
